name: Deploy Storybook

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 25
      - name: Build pages for main branch
        run: |
          git checkout main
          npm ci
          npm run build-storybook
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/
  deploy:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
